### ISSUE TITLE
Can we show playlists as well as single videos?

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-video#3]
Mike Caulfield has produced this amazing playlist of three segments telling the story of historic characters using federated wiki. 

https://www.youtube.com/playlist?list=PLRdZ44gFTfl3hobkAy5P-_51uIcn_h5oj

I've reassembled the three videos of the playlist in a wiki page using three Video Plugins.

http://video.fed.wiki.org/information-lifecycle.html

But maybe this plugin should understand the embed codes for playlists and handle drops of them as well. There is a cost-benefit calculation here, of course. But when our best user makes 'em we should play 'em.

**Comment by paul90** [comment]
Support for YouTube playlist was added some time ago.

For example, the playlist about can be embedded with the following markup.
`YOUTUBE PLAYLIST PLRdZ44gFTfl3hobkAy5P-_51uIcn_h5oj`
